### //create Group
POST http://localhost:8000/api/groups/createGroup
Content-Type: application/json

{
    "group_name": "Sample Group",
    "description": "This is a sample group.",
    "created_by": "8"
}

### //join Group
POST http://localhost:8000/api/groups/joinGroup
Content-Type: application/json


{
  "group_id": 2,
  "user_id": 8
}