### //create Post
POST http://localhost:8000/api/posts/createPost
Content-Type: application/json

{
    "photo_url": "",
    "user_id": "8",
    "content": "This is the content of the postuser id 7 again."
}

### //getAllPosts
POST http://localhost:8000/api/posts/getAllPosts
Content-Type: application/json


### deleteSinglePostController
POST http://localhost:8000/api/posts/4
Content-Type: application/json


### getUserPostsController
GET http://localhost:8000/api/posts/2
Content-Type: application/json


### editPostController
PUT http://localhost:8000/api/posts/editPost
Content-Type: application/json

{
  "post_id": 1,
  "photo_url": "https://example.com/new-photo.jpg",
  "user_id": 6,
  "content": "Updated post content"
}
