
//health check
GET http://localhost:8000/health


### //create user
POST http://localhost:8000/api/users/register 
content-Type: application/json

{
    "first_name": "dev",
    "last_name": "ngecu",
    "username": "ngecu",
    "password": "password123",
    "email": "papam25366@fkcod.com"
}


### //login user
POST http://localhost:8000/api/users/auth/login
content-Type: application/json

{
    "username": "peter",
    "password" : "password123"
}

### //delete user
DELETE http://localhost:8000/api/users/profile/3

#### //get all users
GET http://localhost:8000/api/users/profile/


### //get users by ID
GET http://localhost:8000/api/users/profile/8







